
package cn.itheima.crm.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerServiceImpl", targetNamespace = "http://impl.service.crm.itheima.cn/")

public interface CustomerServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<cn.itheima.crm.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByFixedAreaId", targetNamespace = "http://impl.service.crm.itheima.cn/", className = "cn.itheima.crm.service.FindByFixedAreaId")
    @ResponseWrapper(localName = "findByFixedAreaIdResponse", targetNamespace = "http://impl.service.crm.itheima.cn/", className = "cn.itheima.crm.service.FindByFixedAreaIdResponse")
    public List<Customer> findByFixedAreaId(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "regist", targetNamespace = "http://impl.service.crm.itheima.cn/", className = "cn.itheima.crm.service.Regist")
    @ResponseWrapper(localName = "registResponse", targetNamespace = "http://impl.service.crm.itheima.cn/", className = "cn.itheima.crm.service.RegistResponse")
    public void regist(
        @WebParam(name = "arg0", targetNamespace = "")
        Customer arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findFixedAreaIdByAddress", targetNamespace = "http://impl.service.crm.itheima.cn/", className = "cn.itheima.crm.service.FindFixedAreaIdByAddress")
    @ResponseWrapper(localName = "findFixedAreaIdByAddressResponse", targetNamespace = "http://impl.service.crm.itheima.cn/", className = "cn.itheima.crm.service.FindFixedAreaIdByAddressResponse")
    public String findFixedAreaIdByAddress(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<cn.itheima.crm.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByFixedAreaIdIsNull", targetNamespace = "http://impl.service.crm.itheima.cn/", className = "cn.itheima.crm.service.FindByFixedAreaIdIsNull")
    @ResponseWrapper(localName = "findByFixedAreaIdIsNullResponse", targetNamespace = "http://impl.service.crm.itheima.cn/", className = "cn.itheima.crm.service.FindByFixedAreaIdIsNullResponse")
    public List<Customer> findByFixedAreaIdIsNull();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<cn.itheima.crm.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findFixedAreaIdByCustomer", targetNamespace = "http://impl.service.crm.itheima.cn/", className = "cn.itheima.crm.service.FindFixedAreaIdByCustomer")
    @ResponseWrapper(localName = "findFixedAreaIdByCustomerResponse", targetNamespace = "http://impl.service.crm.itheima.cn/", className = "cn.itheima.crm.service.FindFixedAreaIdByCustomerResponse")
    public List<Customer> findFixedAreaIdByCustomer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<cn.itheima.crm.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://impl.service.crm.itheima.cn/", className = "cn.itheima.crm.service.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://impl.service.crm.itheima.cn/", className = "cn.itheima.crm.service.FindAllResponse")
    public List<Customer> findAll();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "activeMail", targetNamespace = "http://impl.service.crm.itheima.cn/", className = "cn.itheima.crm.service.ActiveMail")
    @ResponseWrapper(localName = "activeMailResponse", targetNamespace = "http://impl.service.crm.itheima.cn/", className = "cn.itheima.crm.service.ActiveMailResponse")
    public void activeMail(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "assignCustomers2FixedArea", targetNamespace = "http://impl.service.crm.itheima.cn/", className = "cn.itheima.crm.service.AssignCustomers2FixedArea")
    @ResponseWrapper(localName = "assignCustomers2FixedAreaResponse", targetNamespace = "http://impl.service.crm.itheima.cn/", className = "cn.itheima.crm.service.AssignCustomers2FixedAreaResponse")
    public String assignCustomers2FixedArea(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<Integer> arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns cn.itheima.crm.service.Customer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByTelephoneAndPassword", targetNamespace = "http://impl.service.crm.itheima.cn/", className = "cn.itheima.crm.service.FindByTelephoneAndPassword")
    @ResponseWrapper(localName = "findByTelephoneAndPasswordResponse", targetNamespace = "http://impl.service.crm.itheima.cn/", className = "cn.itheima.crm.service.FindByTelephoneAndPasswordResponse")
    public Customer findByTelephoneAndPassword(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns cn.itheima.crm.service.Customer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findByTelephone", targetNamespace = "http://impl.service.crm.itheima.cn/", className = "cn.itheima.crm.service.FindByTelephone")
    @ResponseWrapper(localName = "findByTelephoneResponse", targetNamespace = "http://impl.service.crm.itheima.cn/", className = "cn.itheima.crm.service.FindByTelephoneResponse")
    public Customer findByTelephone(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
